// countries.js - Country to cities mapping for the travel itinerary generator
// Each country has a list of major tourist cities

const COUNTRIES = {
    "Afghanistan": ["Kabul", "Herat", "Kandahar", "Mazar-i-Sharif"],
    "Albania": ["Tirana", "Durres", "Vlore", "Saranda", "Shkoder"],
    "Algeria": ["Algiers", "Oran", "Constantine", "Annaba"],
    "Andorra": ["Andorra la Vella", "Escaldes-Engordany"],
    "Angola": ["Luanda", "Lubango", "Benguela"],
    "Antigua and Barbuda": ["St. John's", "English Harbour"],
    "Argentina": ["Buenos Aires", "Cordoba", "Mendoza", "Bariloche", "Ushuaia", "Salta"],
    "Armenia": ["Yerevan", "Gyumri", "Dilijan"],
    "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Cairns", "Gold Coast", "Hobart"],
    "Austria": ["Vienna", "Salzburg", "Innsbruck", "Graz", "Hallstatt"],
    "Azerbaijan": ["Baku", "Ganja", "Sheki"],
    "Bahamas": ["Nassau", "Freeport", "Exuma"],
    "Bahrain": ["Manama", "Muharraq"],
    "Bangladesh": ["Dhaka", "Chittagong", "Cox's Bazar", "Sylhet"],
    "Barbados": ["Bridgetown", "Holetown"],
    "Belarus": ["Minsk", "Brest", "Grodno"],
    "Belgium": ["Brussels", "Bruges", "Ghent", "Antwerp", "Liege"],
    "Belize": ["Belize City", "San Ignacio", "Caye Caulker"],
    "Benin": ["Cotonou", "Porto-Novo"],
    "Bhutan": ["Thimphu", "Paro", "Punakha"],
    "Bolivia": ["La Paz", "Sucre", "Santa Cruz", "Uyuni"],
    "Bosnia and Herzegovina": ["Sarajevo", "Mostar", "Banja Luka"],
    "Botswana": ["Gaborone", "Maun", "Kasane"],
    "Brazil": ["Rio de Janeiro", "Sao Paulo", "Salvador", "Brasilia", "Manaus", "Florianopolis", "Recife"],
    "Brunei": ["Bandar Seri Begawan"],
    "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas"],
    "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso"],
    "Burundi": ["Bujumbura", "Gitega"],
    "Cambodia": ["Phnom Penh", "Siem Reap", "Sihanoukville"],
    "Cameroon": ["Yaounde", "Douala", "Buea"],
    "Canada": ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Quebec City", "Banff", "Victoria"],
    "Cape Verde": ["Praia", "Mindelo"],
    "Central African Republic": ["Bangui"],
    "Chad": ["N'Djamena"],
    "Chile": ["Santiago", "Valparaiso", "Easter Island", "Puerto Natales", "San Pedro de Atacama"],
    "China": ["Beijing", "Shanghai", "Hong Kong", "Xi'an", "Chengdu", "Guangzhou", "Hangzhou", "Guilin"],
    "Colombia": ["Bogota", "Medellin", "Cartagena", "Cali", "Santa Marta"],
    "Comoros": ["Moroni"],
    "Congo (DRC)": ["Kinshasa", "Goma"],
    "Congo (Republic)": ["Brazzaville", "Pointe-Noire"],
    "Costa Rica": ["San Jose", "Liberia", "Puerto Viejo", "La Fortuna", "Monteverde"],
    "Croatia": ["Zagreb", "Dubrovnik", "Split", "Zadar", "Rijeka", "Hvar"],
    "Cuba": ["Havana", "Varadero", "Trinidad", "Santiago de Cuba"],
    "Cyprus": ["Nicosia", "Limassol", "Paphos", "Larnaca"],
    "Czech Republic": ["Prague", "Brno", "Cesky Krumlov", "Karlovy Vary"],
    "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg"],
    "Djibouti": ["Djibouti City"],
    "Dominica": ["Roseau"],
    "Dominican Republic": ["Santo Domingo", "Punta Cana", "Puerto Plata", "La Romana"],
    "Ecuador": ["Quito", "Guayaquil", "Cuenca", "Galapagos Islands", "Banos"],
    "Egypt": ["Cairo", "Alexandria", "Luxor", "Aswan", "Sharm El Sheikh", "Hurghada"],
    "El Salvador": ["San Salvador", "Santa Ana", "San Miguel"],
    "Equatorial Guinea": ["Malabo", "Bata"],
    "Eritrea": ["Asmara", "Massawa"],
    "Estonia": ["Tallinn", "Tartu", "Parnu"],
    "Eswatini": ["Mbabane", "Manzini"],
    "Ethiopia": ["Addis Ababa", "Gondar", "Lalibela", "Axum"],
    "Fiji": ["Suva", "Nadi", "Denarau Island"],
    "Finland": ["Helsinki", "Tampere", "Turku", "Rovaniemi", "Oulu"],
    "France": ["Paris", "Nice", "Lyon", "Marseille", "Bordeaux", "Toulouse", "Strasbourg", "Cannes"],
    "Gabon": ["Libreville", "Port-Gentil"],
    "Gambia": ["Banjul", "Serrekunda"],
    "Georgia": ["Tbilisi", "Batumi", "Kutaisi", "Mtskheta"],
    "Germany": ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne", "Dresden", "Heidelberg", "Stuttgart"],
    "Ghana": ["Accra", "Kumasi", "Cape Coast", "Takoradi"],
    "Greece": ["Athens", "Santorini", "Mykonos", "Thessaloniki", "Crete", "Rhodes", "Corfu"],
    "Grenada": ["St. George's"],
    "Guatemala": ["Guatemala City", "Antigua", "Lake Atitlan", "Flores"],
    "Guinea": ["Conakry"],
    "Guinea-Bissau": ["Bissau"],
    "Guyana": ["Georgetown"],
    "Haiti": ["Port-au-Prince", "Cap-Haitien"],
    "Honduras": ["Tegucigalpa", "San Pedro Sula", "Roatan"],
    "Hungary": ["Budapest", "Debrecen", "Szeged", "Eger"],
    "Iceland": ["Reykjavik", "Akureyri", "Vik", "Hofn"],
    "India": ["New Delhi", "Mumbai", "Jaipur", "Agra", "Goa", "Varanasi", "Kerala", "Udaipur", "Bengaluru"],
    "Indonesia": ["Jakarta", "Bali", "Yogyakarta", "Bandung", "Lombok", "Surabaya"],
    "Iran": ["Tehran", "Isfahan", "Shiraz", "Tabriz", "Mashhad"],
    "Iraq": ["Baghdad", "Erbil", "Basra"],
    "Ireland": ["Dublin", "Cork", "Galway", "Killarney", "Belfast"],
    "Israel": ["Jerusalem", "Tel Aviv", "Haifa", "Eilat", "Dead Sea"],
    "Italy": ["Rome", "Milan", "Venice", "Florence", "Naples", "Amalfi Coast", "Cinque Terre", "Turin"],
    "Ivory Coast": ["Abidjan", "Yamoussoukro"],
    "Jamaica": ["Kingston", "Montego Bay", "Negril", "Ocho Rios"],
    "Japan": ["Tokyo", "Kyoto", "Osaka", "Hiroshima", "Sapporo", "Nara", "Fukuoka", "Okinawa"],
    "Jordan": ["Amman", "Petra", "Wadi Rum", "Aqaba", "Dead Sea"],
    "Kazakhstan": ["Almaty", "Nur-Sultan", "Shymkent"],
    "Kenya": ["Nairobi", "Mombasa", "Diani Beach", "Masai Mara", "Lamu"],
    "Kiribati": ["Tarawa"],
    "Kosovo": ["Pristina", "Prizren"],
    "Kuwait": ["Kuwait City"],
    "Kyrgyzstan": ["Bishkek", "Osh", "Karakol"],
    "Laos": ["Vientiane", "Luang Prabang", "Pakse"],
    "Latvia": ["Riga", "Jurmala", "Liepaja"],
    "Lebanon": ["Beirut", "Byblos", "Tripoli", "Baalbek"],
    "Lesotho": ["Maseru"],
    "Liberia": ["Monrovia"],
    "Libya": ["Tripoli", "Benghazi"],
    "Liechtenstein": ["Vaduz"],
    "Lithuania": ["Vilnius", "Kaunas", "Klaipeda"],
    "Luxembourg": ["Luxembourg City"],
    "Madagascar": ["Antananarivo", "Nosy Be", "Morondava"],
    "Malawi": ["Lilongwe", "Blantyre", "Lake Malawi"],
    "Malaysia": ["Kuala Lumpur", "Penang", "Langkawi", "Malacca", "Kota Kinabalu", "Kuching"],
    "Maldives": ["Male", "Malé Atoll", "Ari Atoll"],
    "Mali": ["Bamako", "Timbuktu", "Mopti"],
    "Malta": ["Valletta", "Sliema", "Gozo"],
    "Marshall Islands": ["Majuro"],
    "Mauritania": ["Nouakchott", "Nouadhibou"],
    "Mauritius": ["Port Louis", "Grand Baie", "Flic en Flac"],
    "Mexico": ["Mexico City", "Cancun", "Playa del Carmen", "Tulum", "Guadalajara", "Oaxaca", "Puerto Vallarta"],
    "Micronesia": ["Palikir"],
    "Moldova": ["Chisinau", "Tiraspol"],
    "Monaco": ["Monaco"],
    "Mongolia": ["Ulaanbaatar", "Karakorum", "Gobi Desert"],
    "Montenegro": ["Podgorica", "Kotor", "Budva", "Herceg Novi"],
    "Morocco": ["Marrakech", "Casablanca", "Fes", "Rabat", "Tangier", "Chefchaouen", "Agadir"],
    "Mozambique": ["Maputo", "Beira", "Tofo Beach"],
    "Myanmar": ["Yangon", "Mandalay", "Bagan", "Inle Lake"],
    "Namibia": ["Windhoek", "Swakopmund", "Etosha National Park", "Sossusvlei"],
    "Nauru": ["Yaren"],
    "Nepal": ["Kathmandu", "Pokhara", "Chitwan", "Lumbini"],
    "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
    "New Zealand": ["Auckland", "Wellington", "Queenstown", "Christchurch", "Rotorua", "Milford Sound"],
    "Nicaragua": ["Managua", "Granada", "Leon", "San Juan del Sur"],
    "Niger": ["Niamey"],
    "Nigeria": ["Lagos", "Abuja", "Port Harcourt", "Kano"],
    "North Korea": ["Pyongyang"],
    "North Macedonia": ["Skopje", "Ohrid", "Bitola"],
    "Norway": ["Oslo", "Bergen", "Tromso", "Stavanger", "Lofoten Islands"],
    "Oman": ["Muscat", "Salalah", "Nizwa", "Sur"],
    "Pakistan": ["Islamabad", "Karachi", "Lahore", "Peshawar", "Quetta", "Multan", "Hunza Valley", "Skardu"],
    "Palau": ["Koror"],
    "Palestine": ["Jerusalem", "Bethlehem", "Ramallah", "Hebron"],
    "Panama": ["Panama City", "Bocas del Toro", "Boquete"],
    "Papua New Guinea": ["Port Moresby", "Rabaul"],
    "Paraguay": ["Asuncion", "Ciudad del Este", "Encarnacion"],
    "Peru": ["Lima", "Cusco", "Machu Picchu", "Arequipa", "Iquitos", "Puno"],
    "Philippines": ["Manila", "Cebu", "Boracay", "Palawan", "Davao", "Bohol"],
    "Poland": ["Warsaw", "Krakow", "Gdansk", "Wroclaw", "Poznan"],
    "Portugal": ["Lisbon", "Porto", "Faro", "Madeira", "Sintra", "Coimbra"],
    "Qatar": ["Doha"],
    "Romania": ["Bucharest", "Cluj-Napoca", "Brasov", "Sibiu", "Timisoara"],
    "Russia": ["Moscow", "Saint Petersburg", "Kazan", "Sochi", "Vladivostok"],
    "Rwanda": ["Kigali", "Volcanoes National Park"],
    "Saint Kitts and Nevis": ["Basseterre", "Charlestown"],
    "Saint Lucia": ["Castries", "Gros Islet"],
    "Saint Vincent and the Grenadines": ["Kingstown"],
    "Samoa": ["Apia"],
    "San Marino": ["San Marino"],
    "Sao Tome and Principe": ["Sao Tome"],
    "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "AlUla"],
    "Senegal": ["Dakar", "Saint-Louis", "Goree Island"],
    "Serbia": ["Belgrade", "Novi Sad", "Nis"],
    "Seychelles": ["Victoria", "Praslin", "La Digue"],
    "Sierra Leone": ["Freetown"],
    "Singapore": ["Singapore"],
    "Slovakia": ["Bratislava", "Kosice", "Tatras"],
    "Slovenia": ["Ljubljana", "Bled", "Maribor", "Piran"],
    "Solomon Islands": ["Honiara"],
    "Somalia": ["Mogadishu", "Hargeisa"],
    "South Africa": ["Cape Town", "Johannesburg", "Durban", "Kruger National Park", "Garden Route", "Pretoria"],
    "South Korea": ["Seoul", "Busan", "Jeju Island", "Incheon", "Gyeongju"],
    "South Sudan": ["Juba"],
    "Spain": ["Madrid", "Barcelona", "Seville", "Valencia", "Granada", "Bilbao", "Mallorca", "Tenerife"],
    "Sri Lanka": ["Colombo", "Kandy", "Galle", "Sigiriya", "Ella", "Negombo"],
    "Sudan": ["Khartoum", "Meroe"],
    "Suriname": ["Paramaribo"],
    "Sweden": ["Stockholm", "Gothenburg", "Malmo", "Uppsala", "Kiruna"],
    "Switzerland": ["Zurich", "Geneva", "Bern", "Lucerne", "Interlaken", "Zermatt", "Lausanne"],
    "Syria": ["Damascus", "Aleppo", "Palmyra"],
    "Taiwan": ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Hualien"],
    "Tajikistan": ["Dushanbe", "Khujand", "Pamir Mountains"],
    "Tanzania": ["Dar es Salaam", "Zanzibar", "Arusha", "Serengeti", "Kilimanjaro"],
    "Thailand": ["Bangkok", "Phuket", "Chiang Mai", "Pattaya", "Krabi", "Koh Samui", "Ayutthaya"],
    "Timor-Leste": ["Dili"],
    "Togo": ["Lome"],
    "Tonga": ["Nuku'alofa"],
    "Trinidad and Tobago": ["Port of Spain", "Tobago"],
    "Tunisia": ["Tunis", "Sousse", "Hammamet", "Djerba"],
    "Turkey": ["Istanbul", "Ankara", "Cappadocia", "Antalya", "Izmir", "Bodrum", "Pamukkale"],
    "Turkmenistan": ["Ashgabat", "Merv"],
    "Tuvalu": ["Funafuti"],
    "Uganda": ["Kampala", "Entebbe", "Bwindi Impenetrable Forest"],
    "Ukraine": ["Kyiv", "Lviv", "Odesa", "Kharkiv"],
    "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ras Al Khaimah"],
    "United Kingdom": ["London", "Edinburgh", "Manchester", "Birmingham", "Liverpool", "Bath", "York", "Glasgow"],
    "United States": ["New York", "Los Angeles", "Chicago", "San Francisco", "Miami", "Las Vegas", "Seattle", "Boston", "Washington DC", "New Orleans", "Hawaii", "Orlando"],
    "Uruguay": ["Montevideo", "Punta del Este", "Colonia del Sacramento"],
    "Uzbekistan": ["Tashkent", "Samarkand", "Bukhara", "Khiva"],
    "Vanuatu": ["Port Vila"],
    "Vatican City": ["Vatican City"],
    "Venezuela": ["Caracas", "Margarita Island", "Angel Falls"],
    "Vietnam": ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hoi An", "Hue", "Nha Trang", "Ha Long Bay"],
    "Yemen": ["Sana'a", "Aden", "Socotra"],
    "Zambia": ["Lusaka", "Livingstone", "Victoria Falls"],
    "Zimbabwe": ["Harare", "Victoria Falls", "Bulawayo", "Great Zimbabwe", "Hwange National Park"]
};