// currencies.js - World currencies with symbols and country mapping
// Used for custom budget auto-detection based on source country

const CURRENCIES = {
    "AED": { name: "UAE Dirham", symbol: "د.إ", countries: ["United Arab Emirates"] },
    "AFN": { name: "Afghan Afghani", symbol: "؋", countries: ["Afghanistan"] },
    "ALL": { name: "Albanian Lek", symbol: "L", countries: ["Albania"] },
    "AMD": { name: "Armenian Dram", symbol: "֏", countries: ["Armenia"] },
    "ANG": { name: "Netherlands Antillean Guilder", symbol: "ƒ", countries: ["Curaçao", "Sint Maarten"] },
    "AOA": { name: "Angolan Kwanza", symbol: "Kz", countries: ["Angola"] },
    "ARS": { name: "Argentine Peso", symbol: "$", countries: ["Argentina"] },
    "AUD": { name: "Australian Dollar", symbol: "A$", countries: ["Australia", "Kiribati", "Nauru", "Tuvalu"] },
    "AWG": { name: "Aruban Florin", symbol: "ƒ", countries: ["Aruba"] },
    "AZN": { name: "Azerbaijani Manat", symbol: "₼", countries: ["Azerbaijan"] },
    "BAM": { name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM", countries: ["Bosnia and Herzegovina"] },
    "BBD": { name: "Barbadian Dollar", symbol: "Bds$", countries: ["Barbados"] },
    "BDT": { name: "Bangladeshi Taka", symbol: "৳", countries: ["Bangladesh"] },
    "BGN": { name: "Bulgarian Lev", symbol: "лв", countries: ["Bulgaria"] },
    "BHD": { name: "Bahraini Dinar", symbol: ".د.ب", countries: ["Bahrain"] },
    "BIF": { name: "Burundian Franc", symbol: "FBu", countries: ["Burundi"] },
    "BMD": { name: "Bermudian Dollar", symbol: "$", countries: ["Bermuda"] },
    "BND": { name: "Brunei Dollar", symbol: "B$", countries: ["Brunei"] },
    "BOB": { name: "Bolivian Boliviano", symbol: "Bs.", countries: ["Bolivia"] },
    "BRL": { name: "Brazilian Real", symbol: "R$", countries: ["Brazil"] },
    "BSD": { name: "Bahamian Dollar", symbol: "B$", countries: ["Bahamas"] },
    "BTN": { name: "Bhutanese Ngultrum", symbol: "Nu.", countries: ["Bhutan"] },
    "BWP": { name: "Botswana Pula", symbol: "P", countries: ["Botswana"] },
    "BYN": { name: "Belarusian Ruble", symbol: "Br", countries: ["Belarus"] },
    "BZD": { name: "Belize Dollar", symbol: "BZ$", countries: ["Belize"] },
    "CAD": { name: "Canadian Dollar", symbol: "C$", countries: ["Canada"] },
    "CDF": { name: "Congolese Franc", symbol: "FC", countries: ["Congo (DRC)"] },
    "CHF": { name: "Swiss Franc", symbol: "CHF", countries: ["Switzerland", "Liechtenstein"] },
    "CLP": { name: "Chilean Peso", symbol: "$", countries: ["Chile"] },
    "CNY": { name: "Chinese Yuan", symbol: "¥", countries: ["China"] },
    "COP": { name: "Colombian Peso", symbol: "$", countries: ["Colombia"] },
    "CRC": { name: "Costa Rican Colón", symbol: "₡", countries: ["Costa Rica"] },
    "CUP": { name: "Cuban Peso", symbol: "$", countries: ["Cuba"] },
    "CVE": { name: "Cape Verdean Escudo", symbol: "$", countries: ["Cape Verde"] },
    "CZK": { name: "Czech Koruna", symbol: "Kč", countries: ["Czech Republic"] },
    "DJF": { name: "Djiboutian Franc", symbol: "Fdj", countries: ["Djibouti"] },
    "DKK": { name: "Danish Krone", symbol: "kr", countries: ["Denmark", "Greenland", "Faroe Islands"] },
    "DOP": { name: "Dominican Peso", symbol: "RD$", countries: ["Dominican Republic"] },
    "DZD": { name: "Algerian Dinar", symbol: "دج", countries: ["Algeria"] },
    "EGP": { name: "Egyptian Pound", symbol: "E£", countries: ["Egypt"] },
    "ERN": { name: "Eritrean Nakfa", symbol: "Nfk", countries: ["Eritrea"] },
    "ETB": { name: "Ethiopian Birr", symbol: "Br", countries: ["Ethiopia"] },
    "EUR": { name: "Euro", symbol: "€", countries: ["France", "Germany", "Italy", "Spain", "Portugal", "Netherlands", "Belgium", "Austria", "Ireland", "Greece", "Finland", "Slovakia", "Slovenia", "Croatia", "Cyprus", "Estonia", "Latvia", "Lithuania", "Luxembourg", "Malta", "Monaco", "Andorra", "San Marino", "Vatican City", "Kosovo", "Montenegro"] },
    "FJD": { name: "Fijian Dollar", symbol: "FJ$", countries: ["Fiji"] },
    "GBP": { name: "British Pound", symbol: "£", countries: ["United Kingdom"] },
    "GEL": { name: "Georgian Lari", symbol: "₾", countries: ["Georgia"] },
    "GHS": { name: "Ghanaian Cedi", symbol: "₵", countries: ["Ghana"] },
    "GMD": { name: "Gambian Dalasi", symbol: "D", countries: ["Gambia"] },
    "GNF": { name: "Guinean Franc", symbol: "FG", countries: ["Guinea"] },
    "GTQ": { name: "Guatemalan Quetzal", symbol: "Q", countries: ["Guatemala"] },
    "GYD": { name: "Guyanese Dollar", symbol: "G$", countries: ["Guyana"] },
    "HKD": { name: "Hong Kong Dollar", symbol: "HK$", countries: ["Hong Kong"] },
    "HNL": { name: "Honduran Lempira", symbol: "L", countries: ["Honduras"] },
    "HTG": { name: "Haitian Gourde", symbol: "G", countries: ["Haiti"] },
    "HUF": { name: "Hungarian Forint", symbol: "Ft", countries: ["Hungary"] },
    "IDR": { name: "Indonesian Rupiah", symbol: "Rp", countries: ["Indonesia"] },
    "ILS": { name: "Israeli New Shekel", symbol: "₪", countries: ["Israel"] },
    "INR": { name: "Indian Rupee", symbol: "₹", countries: ["India"] },
    "IQD": { name: "Iraqi Dinar", symbol: "ع.د", countries: ["Iraq"] },
    "IRR": { name: "Iranian Rial", symbol: "﷼", countries: ["Iran"] },
    "ISK": { name: "Icelandic Króna", symbol: "kr", countries: ["Iceland"] },
    "JMD": { name: "Jamaican Dollar", symbol: "J$", countries: ["Jamaica"] },
    "JOD": { name: "Jordanian Dinar", symbol: "د.ا", countries: ["Jordan"] },
    "JPY": { name: "Japanese Yen", symbol: "¥", countries: ["Japan"] },
    "KES": { name: "Kenyan Shilling", symbol: "KSh", countries: ["Kenya"] },
    "KGS": { name: "Kyrgyzstani Som", symbol: "с", countries: ["Kyrgyzstan"] },
    "KHR": { name: "Cambodian Riel", symbol: "៛", countries: ["Cambodia"] },
    "KMF": { name: "Comorian Franc", symbol: "CF", countries: ["Comoros"] },
    "KRW": { name: "South Korean Won", symbol: "₩", countries: ["South Korea"] },
    "KWD": { name: "Kuwaiti Dinar", symbol: "د.ك", countries: ["Kuwait"] },
    "KYD": { name: "Cayman Islands Dollar", symbol: "CI$", countries: ["Cayman Islands"] },
    "KZT": { name: "Kazakhstani Tenge", symbol: "₸", countries: ["Kazakhstan"] },
    "LAK": { name: "Lao Kip", symbol: "₭", countries: ["Laos"] },
    "LBP": { name: "Lebanese Pound", symbol: "ل.ل", countries: ["Lebanon"] },
    "LKR": { name: "Sri Lankan Rupee", symbol: "Rs", countries: ["Sri Lanka"] },
    "LRD": { name: "Liberian Dollar", symbol: "L$", countries: ["Liberia"] },
    "LSL": { name: "Lesotho Loti", symbol: "L", countries: ["Lesotho"] },
    "LYD": { name: "Libyan Dinar", symbol: "ل.د", countries: ["Libya"] },
    "MAD": { name: "Moroccan Dirham", symbol: "د.م.", countries: ["Morocco"] },
    "MDL": { name: "Moldovan Leu", symbol: "L", countries: ["Moldova"] },
    "MGA": { name: "Malagasy Ariary", symbol: "Ar", countries: ["Madagascar"] },
    "MKD": { name: "Macedonian Denar", symbol: "ден", countries: ["North Macedonia"] },
    "MMK": { name: "Myanmar Kyat", symbol: "K", countries: ["Myanmar"] },
    "MNT": { name: "Mongolian Tögrög", symbol: "₮", countries: ["Mongolia"] },
    "MOP": { name: "Macanese Pataca", symbol: "MOP$", countries: ["Macau"] },
    "MRU": { name: "Mauritanian Ouguiya", symbol: "UM", countries: ["Mauritania"] },
    "MUR": { name: "Mauritian Rupee", symbol: "₨", countries: ["Mauritius"] },
    "MVR": { name: "Maldivian Rufiyaa", symbol: "Rf", countries: ["Maldives"] },
    "MWK": { name: "Malawian Kwacha", symbol: "MK", countries: ["Malawi"] },
    "MXN": { name: "Mexican Peso", symbol: "Mex$", countries: ["Mexico"] },
    "MYR": { name: "Malaysian Ringgit", symbol: "RM", countries: ["Malaysia"] },
    "MZN": { name: "Mozambican Metical", symbol: "MT", countries: ["Mozambique"] },
    "NAD": { name: "Namibian Dollar", symbol: "N$", countries: ["Namibia"] },
    "NGN": { name: "Nigerian Naira", symbol: "₦", countries: ["Nigeria"] },
    "NIO": { name: "Nicaraguan Córdoba", symbol: "C$", countries: ["Nicaragua"] },
    "NOK": { name: "Norwegian Krone", symbol: "kr", countries: ["Norway"] },
    "NPR": { name: "Nepalese Rupee", symbol: "₨", countries: ["Nepal"] },
    "NZD": { name: "New Zealand Dollar", symbol: "NZ$", countries: ["New Zealand"] },
    "OMR": { name: "Omani Rial", symbol: "ر.ع.", countries: ["Oman"] },
    "PAB": { name: "Panamanian Balboa", symbol: "B/.", countries: ["Panama"] },
    "PEN": { name: "Peruvian Sol", symbol: "S/", countries: ["Peru"] },
    "PGK": { name: "Papua New Guinean Kina", symbol: "K", countries: ["Papua New Guinea"] },
    "PHP": { name: "Philippine Peso", symbol: "₱", countries: ["Philippines"] },
    "PKR": { name: "Pakistani Rupee", symbol: "₨", countries: ["Pakistan"] },
    "PLN": { name: "Polish Złoty", symbol: "zł", countries: ["Poland"] },
    "PYG": { name: "Paraguayan Guaraní", symbol: "₲", countries: ["Paraguay"] },
    "QAR": { name: "Qatari Riyal", symbol: "ر.ق", countries: ["Qatar"] },
    "RON": { name: "Romanian Leu", symbol: "lei", countries: ["Romania"] },
    "RSD": { name: "Serbian Dinar", symbol: "дин", countries: ["Serbia"] },
    "RUB": { name: "Russian Ruble", symbol: "₽", countries: ["Russia"] },
    "RWF": { name: "Rwandan Franc", symbol: "FRw", countries: ["Rwanda"] },
    "SAR": { name: "Saudi Riyal", symbol: "ر.س", countries: ["Saudi Arabia"] },
    "SBD": { name: "Solomon Islands Dollar", symbol: "SI$", countries: ["Solomon Islands"] },
    "SCR": { name: "Seychellois Rupee", symbol: "₨", countries: ["Seychelles"] },
    "SDG": { name: "Sudanese Pound", symbol: "ج.س", countries: ["Sudan"] },
    "SEK": { name: "Swedish Krona", symbol: "kr", countries: ["Sweden"] },
    "SGD": { name: "Singapore Dollar", symbol: "S$", countries: ["Singapore"] },
    "SLL": { name: "Sierra Leonean Leone", symbol: "Le", countries: ["Sierra Leone"] },
    "SOS": { name: "Somali Shilling", symbol: "Sh", countries: ["Somalia"] },
    "SRD": { name: "Surinamese Dollar", symbol: "$", countries: ["Suriname"] },
    "SSP": { name: "South Sudanese Pound", symbol: "£", countries: ["South Sudan"] },
    "STN": { name: "São Tomé and Príncipe Dobra", symbol: "Db", countries: ["Sao Tome and Principe"] },
    "SYP": { name: "Syrian Pound", symbol: "£S", countries: ["Syria"] },
    "SZL": { name: "Swazi Lilangeni", symbol: "L", countries: ["Eswatini"] },
    "THB": { name: "Thai Baht", symbol: "฿", countries: ["Thailand"] },
    "TJS": { name: "Tajikistani Somoni", symbol: "ЅМ", countries: ["Tajikistan"] },
    "TMT": { name: "Turkmenistani Manat", symbol: "m", countries: ["Turkmenistan"] },
    "TND": { name: "Tunisian Dinar", symbol: "د.ت", countries: ["Tunisia"] },
    "TOP": { name: "Tongan Paʻanga", symbol: "T$", countries: ["Tonga"] },
    "TRY": { name: "Turkish Lira", symbol: "₺", countries: ["Turkey"] },
    "TTD": { name: "Trinidad and Tobago Dollar", symbol: "TT$", countries: ["Trinidad and Tobago"] },
    "TWD": { name: "New Taiwan Dollar", symbol: "NT$", countries: ["Taiwan"] },
    "TZS": { name: "Tanzanian Shilling", symbol: "TSh", countries: ["Tanzania"] },
    "UAH": { name: "Ukrainian Hryvnia", symbol: "₴", countries: ["Ukraine"] },
    "UGX": { name: "Ugandan Shilling", symbol: "USh", countries: ["Uganda"] },
    "USD": { name: "US Dollar", symbol: "$", countries: ["United States", "Ecuador", "El Salvador", "Panama", "Zimbabwe", "Puerto Rico", "Guam", "US Virgin Islands", "American Samoa", "Northern Mariana Islands", "Marshall Islands", "Micronesia", "Palau", "Timor-Leste"] },
    "UYU": { name: "Uruguayan Peso", symbol: "$U", countries: ["Uruguay"] },
    "UZS": { name: "Uzbekistani Som", symbol: "so'm", countries: ["Uzbekistan"] },
    "VES": { name: "Venezuelan Bolívar", symbol: "Bs", countries: ["Venezuela"] },
    "VND": { name: "Vietnamese Đồng", symbol: "₫", countries: ["Vietnam"] },
    "VUV": { name: "Vanuatu Vatu", symbol: "VT", countries: ["Vanuatu"] },
    "WST": { name: "Samoan Tālā", symbol: "T", countries: ["Samoa"] },
    "XAF": { name: "Central African CFA Franc", symbol: "FCFA", countries: ["Cameroon", "Central African Republic", "Chad", "Congo (Republic)", "Equatorial Guinea", "Gabon"] },
    "XCD": { name: "East Caribbean Dollar", symbol: "EC$", countries: ["Antigua and Barbuda", "Dominica", "Grenada", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines"] },
    "XOF": { name: "West African CFA Franc", symbol: "CFA", countries: ["Benin", "Burkina Faso", "Ivory Coast", "Guinea-Bissau", "Mali", "Niger", "Senegal", "Togo"] },
    "XPF": { name: "CFP Franc", symbol: "₣", countries: ["French Polynesia", "New Caledonia"] },
    "YER": { name: "Yemeni Rial", symbol: "﷼", countries: ["Yemen"] },
    "ZAR": { name: "South African Rand", symbol: "R", countries: ["South Africa", "Lesotho", "Namibia", "Eswatini"] },
    "ZMW": { name: "Zambian Kwacha", symbol: "ZK", countries: ["Zambia"] },
    "ZWL": { name: "Zimbabwean Dollar", symbol: "Z$", countries: ["Zimbabwe"] }
};

// Helper: Get currency code for a country
function getCurrencyForCountry(country) {
    for (const [code, data] of Object.entries(CURRENCIES)) {
        if (data.countries.includes(country)) {
            return code;
        }
    }
    return 'USD'; // Default fallback
}